// Automatically generated by Interoptopus.

#ifndef meocap_sdk
#define meocap_sdk

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>




    typedef struct joint
    {
        double pos[3];
        double glb_rot[4];
        double loc_rot[4];
    } joint;

    typedef struct skeljoint
    {
        double pos[3];
    } skeljoint;

    typedef struct meoframe
    {
        int32_t frame_id;
        double translation[3];
        joint joints[24];
    } meoframe;

    typedef struct skelbase
    {
        skeljoint bones[24];
        double floor_y;
    } skelbase;


    uint64_t meocap_connect_server_char(uint8_t ip_a, uint8_t ip_b, uint8_t ip_c, uint8_t ip_d, uint16_t port);

    uint64_t meocap_connect_server_cstr(const int8_t* endpoint);

    uint64_t meocap_connect_command_server_char(uint8_t ip_a, uint8_t ip_b, uint8_t ip_c, uint8_t ip_d, uint16_t port);

    uint64_t meocap_connect_command_server_cstr(const int8_t* endpoint);

    int32_t meocap_command_set_skel(uint64_t socket, const skelbase* skel);

    int32_t meocap_recv_frame(uint64_t socket, meoframe* frame_buf);

    int32_t meocap_clean_up(uint64_t socket);

    int32_t meocap_hello(int32_t input);


#ifdef __cplusplus
}
#endif

#endif /* meocap_sdk */
